apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: dag-
spec:
  entrypoint: main
  templates:
    - name: main
      dag:
        tasks:
          - name: a
            template: echo
          - name: b
            template: echo
            dependencies:
              - a
          - name: c
            template: echo
            dependencies:
              - a
              - b
    - name: echo
      container:
        image: busybox
        command: [ echo ]
        args: [ "hello world" ]